version: "3.9"

services:
  web:
    build: .
    env_file:
      - .env
    environment:
      -REDIS_HOST: redis
      -REDIS_PORT: 6379
    restart: unless-stopped

    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - web
    
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
